
# Build settings
gems:
#   - jemoji # emoji plugin
  - jekyll-paginate

# Site settings
title: מדברים בסרט
# description: > # this means to ignore newlines until "email:"
description: ערוץ הקומנטרי של בתי הקולנוע

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: /assets/images/podcast.jpg

# name: 'Dirk Fabisch'
# author: 'Dirk Fabisch'
# author_image: "/assets/images/author.jpg"

paginate:	5

# url: http://***.*** # the base hostname & protocol for your site
# baseurl: movietalker.com
#used to display twitter cards
twitter_handle: '@MovieTalkerCast'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/MovieTalkerCast
    desc: פה אנחנו מצייצים
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/MovieTalkerCast/
    desc: בקרו אותנו בפייסבוק
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/dirkfabisch
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:


###############################################################
# # Jekyll
# theme: jekyll-theme-architect
# highlighter: rouge
# encoding: bom|utf-8

# #Website
# title: מדברים בסרט
# description: ערוץ הקומנטרי של בתי הקולנוע
# show_downloads: false
# google_analytics: true

permalink: /:title/
# url: http://www.movietalker.com

# exclude:
#  - Gemfile
#  - Gemfile.lock
#  - README.md


# twitter_username: MovieTalkerCast
# facebook:
#  app_id: 1521883347835573
#  publisher: https://www.facebook.com/MovieTalkerCast/

# gems:
#  - jekyll-seo-tag

# include: ['episodes']
