
# Build settings
plugins:
  - jekyll-paginate

# Site settings
title: מדברים בסרט
# description: > # this means to ignore newlines until "email:"
description: מדברים בסרט, פודקסט בערך על סרטים

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: /assets/images/podcast.jpg

# name: 'Dirk Fabisch'
# author: 'Dirk Fabisch'
# author_image: "/assets/images/author.jpg"

paginate:	10

# url: http://***.*** # the base hostname & protocol for your site
# baseurl: movietalker.com
#used to display twitter cards
twitter_handle: '@MovieTalkerCast'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/MovieTalkerCast
    desc: פה אנחנו מצייצים
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/MovieTalkerCast/
    desc: בקרו אותנו בפייסבוק
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

permalink: /episodes/:title/

# exclude:
#  - Gemfile
#  - Gemfile.lock
#  - README.md
