theme: jekyll-theme-architect
title: מדברים בסרט
description: ערוץ הקומנטרי של בתי הקולנוע
show_downloads: false
google_analytics: true
highlighter: rouge
encoding: bom|utf-8
permalink: /:title/

exclude:
 - Gemfile
 - Gemfile.lock
 - README.md

url: http://www.movietalker.com
twitter_username: MovieTalkerCast
facebook:
 app_id: 1706357636323233
 publisher: https://www.facebook.com/MovieTalkerCast/

gems:
 - jekyll-seo-tag

include: ['episodes']
